name: Rollback (Azure by digest)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'staging | production'
        required: true
        default: 'production'
      digest:
        description: 'Image digest (sha256:...)'
        required: true

jobs:
  redeploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set app name
        id: setname
        run: |
          if [ "${{ inputs.environment }}" = "staging" ]; then
            echo "APP=${{ secrets.AZURE_WEBAPP_STAGING }}" >> $GITHUB_OUTPUT
          else
            echo "APP=${{ secrets.AZURE_WEBAPP_PROD }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy digest
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ steps.setname.outputs.APP }}
          images: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}@${{ inputs.digest }}
